name: Get All Changed Files
description: Get all of the files changed/modified in a pull request or push's commits, make sure package.json and/or package-lock.json are not submitted with other files.
author: jomendez.
branding:
  icon: file
  color: blue
runs:
  using: node12
  main: dist/index.js
inputs:
  token:
    description: >
      GitHub token for GitHub API requests.
      Users shouldn't need to set this themselves.
    required: true
    default: ${{ github.token }}
outputs:
  all:
    description: >
      Array of all changed files.
  added:
    description: >
      Array of added files.
  modified:
    description: >
      Array of modified files.
  removed:
    description: >
      Array of removed files.
  renamed:
    description: >
      Array of renamed files.
  added_modified:
    description: >
      Array of all added and modified files.
  # For backwards-compatibility
  deleted:
    description: >
      Array of deleted files.
